### ISSUE TITLE
error EPROTO results when pin folder with 10K items

### ISSUE THREAD

**Issue by dohomi** [PinataCloud/Pinata-SDK#86]
Hi Guys,

I try to pin a folder with 10K NFT files. The SDK seems not to be able to handle the request:
```
╰─$ node uploadToPinata.js
Error: write EPROTO 4572933632:error:140D010F:SSL routines:SSL_write:bad length:../deps/openssl/openssl/ssl/ssl_lib.c:1970:

    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writevGeneric (internal/stream_base_commons.js:139:3)
    at TLSSocket.Socket._writeGeneric (net.js:785:11)
    at TLSSocket.Socket._writev (net.js:794:8)
    at doWrite (internal/streams/writable.js:375:12)
    at clearBuffer (internal/streams/writable.js:521:5)
    at onwrite (internal/streams/writable.js:430:7)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:103:10) {
  errno: -100,
  code: 'EPROTO',
  syscall: 'write',
  config: {
    url: 'https://api.pinata.cloud/pinning/pinFileToIPFS',
```
If I try the same script with a different folder and smaller amount of files it works.

**Comment by tinmarr** [comment]
Any update on this? I'm having the same issue.

**Comment by rommel-pinata** [comment]
Hello, @dohomi and @tinmarr I tried uploading simple JSON, images, and videos. However, I don't see any issue. I do change the way the files are uploaded so it doesn't have a memory leak.
