### ISSUE TITLE
Error: only one instance of `babel-polyfill` is allowed

### ISSUE THREAD

**Issue by GonzaloHirschToptal** [PinataCloud/Pinata-SDK#97]
I'm currently implementing the Pinata SDK in a Serverless environment (using the Serverless Framework), and I'm encountering the following error

<details>
<summary>See full stacktrace</summary>
<pre><code>
Error: only one instance of babel-polyfill is allowed
    at Object../node_modules/babel-polyfill/lib/index.js (/REDACTED_PROJECT_DIR/node_modules/@pinata/sdk/lib/pinata-sdk.js:2782:9)
    at __webpack_require__ (/REDACTED_PROJECT_DIR/node_modules/@pinata/sdk/lib/pinata-sdk.js:30:30)
    at Object.0 (/REDACTED_PROJECT_DIR/node_modules/@pinata/sdk/lib/pinata-sdk.js:24016:1)
    at __webpack_require__ (/REDACTED_PROJECT_DIR/node_modules/@pinata/sdk/lib/pinata-sdk.js:30:30)
    at /REDACTED_PROJECT_DIR/node_modules/@pinata/sdk/lib/pinata-sdk.js:94:18
    at /REDACTED_PROJECT_DIR/node_modules/@pinata/sdk/lib/pinata-sdk.js:97:10
    at webpackUniversalModuleDefinition (/REDACTED_PROJECT_DIR/node_modules/@pinata/sdk/lib/pinata-sdk.js:3:20)
    at Object.<anonymous> (/REDACTED_PROJECT_DIR/node_modules/@pinata/sdk/lib/pinata-sdk.js:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.@pinata/sdk (/REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:240487)
    at __webpack_require__ (/REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:240910)
    at eval (webpack-internal:///./src/services/ipfs.service.ts:6:31)
    at Object../src/services/ipfs.service.ts (/REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:203985)
    at __webpack_require__ (/REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:240910)
    at eval (webpack-internal:///./src/services/interaction.service.ts:14:40)
    at Object../src/services/interaction.service.ts (/REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:181908)
    at __webpack_require__ (/REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:240910)
    at eval (webpack-internal:///./src/handlers/contracts/postInteractContract.ts:14:47)
    at Object../src/handlers/contracts/postInteractContract.ts (/REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:92934)
    at __webpack_require__ (/REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:240910)
    at /REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:240992
    at Object.<anonymous> (/REDACTED_PROJECT_DIR/.webpack/service/src/handlers/contracts/postInteractContract.js:2:241289)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at /REDACTED_PROJECT_DIR/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:157:133
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async InProcessRunner.run (/REDACTED_PROJECT_DIR/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:157:9)
</code></pre>
</details>

From what I understand, both the Serverless Framework and the Pinata SDK load `babel-polyfill`. I'm aware that this error doesn't occur in production, but in local development it does, and it reduces our ability to locally test our code.

Is it possible to change the include mechanism as per [this response in an issue](https://github.com/babel/babel-loader/issues/401#issuecomment-365650944)? Otherwise any library that also uses this polyfill will have the same error when working with Pinata.

**Comment by tkjwa** [comment]
Hello, I've hit the same issue in a different context, I was indeed loading the SDK twice, so the bug kinda helped me stop a design issue on my side ^^
In addition to the solution linked by @GonzaloHirschToptal , maybe you could keep a warning 
Thank you

**Comment by rommel-pinata** [comment]
I added a PR that could fix this issue!

**Comment by rommel-pinata** [comment]
This PR mas release should no longer an issue.
